# Generated by Django 3.0.4 on 2020-04-03 17:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=20)),
                ('address_line1', models.CharField(max_length=20)),
                ('address_line2', models.CharField(max_length=20)),
                ('address_postcode', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('images', models.ImageField(blank=True, upload_to='gym_images')),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(default=0, max_length=14)),
                ('specialism', models.CharField(default='N/A', max_length=512)),
                ('sex', models.CharField(default='unspecified', max_length=16)),
                ('img', models.ImageField(blank=True, default=None, upload_to='trainerProfile_images')),
                ('price', models.CharField(default='unknown', max_length=10)),
                ('g_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='ptfinderApp.Gym')),
                ('t_account', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=512)),
                ('sex', models.CharField(max_length=16)),
                ('location', models.CharField(max_length=30)),
                ('img', models.ImageField(blank=True, upload_to='userProfile_images')),
                ('account', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=512)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2020, 4, 3, 18, 49, 30, 284007))),
                ('t_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptfinderApp.Trainer')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptfinderApp.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2020, 4, 3, 18, 49, 30, 284007))),
                ('location', models.CharField(max_length=30)),
                ('trainer_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptfinderApp.Trainer')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptfinderApp.UserProfile')),
            ],
        ),
    ]
