# Generated by Django 3.0.4 on 2020-03-19 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=20)),
                ('address_line1', models.CharField(max_length=20)),
                ('address_line2', models.CharField(max_length=20)),
                ('address_postcode', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('images', models.ImageField(blank=True, upload_to='gym_images')),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_username', models.CharField(max_length=30, unique=True)),
                ('firstname', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=14)),
                ('specialism', models.CharField(max_length=512)),
                ('sex', models.CharField(max_length=16)),
                ('img', models.ImageField(blank=True, upload_to='trainerProfile_images')),
                ('price', models.CharField(max_length=10)),
                ('g_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptfinderApp.Gym')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('firstname', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.CharField(max_length=512)),
                ('sex', models.CharField(max_length=16)),
                ('location', models.CharField(max_length=30)),
                ('img', models.ImageField(blank=True, upload_to='userProfile_images')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=512)),
                ('datetime', models.DateField()),
                ('t_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptfinderApp.Trainer')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptfinderApp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField()),
                ('location', models.CharField(max_length=30)),
                ('t_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptfinderApp.Trainer')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptfinderApp.User')),
            ],
        ),
    ]
