# Generated by Django 3.0.4 on 2020-03-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptfinderApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
    ]
