# Generated by Django 3.0.4 on 2020-03-20 15:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ptfinderApp', '0002_auto_20200319_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='contact_no',
            field=models.CharField(default=0, max_length=14),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='firstname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='g_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ptfinderApp.Gym'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='price',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='sex',
            field=models.CharField(default='unspecified', max_length=16),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialism',
            field=models.CharField(default='N/A', max_length=512),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='surname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='t_username',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='trainer_comment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 15, 47, 49, 699819)),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=512)),
                ('sex', models.CharField(max_length=16)),
                ('location', models.CharField(max_length=30)),
                ('img', models.ImageField(blank=True, upload_to='userProfile_images')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptfinderApp.UserProfile'),
        ),
        migrations.AlterField(
            model_name='trainer_comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptfinderApp.UserProfile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
