# Generated by Django 3.0.4 on 2020-04-01 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptfinderApp', '0005_auto_20200331_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 15, 47, 15, 38043)),
        ),
        migrations.AlterField(
            model_name='trainer_comment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 15, 47, 15, 40451)),
        ),
    ]
