# Generated by Django 3.0.4 on 2020-04-01 15:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptfinderApp', '0006_auto_20200401_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 16, 12, 6, 598317)),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='g_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='ptfinderApp.Gym'),
        ),
        migrations.AlterField(
            model_name='trainer_comment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 16, 12, 6, 598317)),
        ),
    ]
